package com.tecapro.inventory.common.dao;

import com.tecapro.inventory.common.exception.UniqueKeyException;
import com.tecapro.inventory.common.model.Admin;
import com.tecapro.inventory.common.model.AdminKey;

public interface AdminDao {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table admin
     *
     * @author MbGenerated
     */
    int selectCount(Admin record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table admin
     *
     * @author MbGenerated
     */
    Admin selectByPK(AdminKey key);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table admin
     *
     * @author MbGenerated
     */
    Admin selectForUpdateByPK(AdminKey key);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table admin
     *
     * @author MbGenerated
     */
    int insert(Admin record) throws UniqueKeyException;

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table admin
     *
     * @author MbGenerated
     */
    int update(Admin record) throws Throwable;

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table admin
     *
     * @author MbGenerated
     */
    int deleteByPK(AdminKey key) throws Throwable;
}