package com.tecapro.inventory.common.model;

import java.io.Serializable;

public class AdminRightKey implements Serializable {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table admin_right
     *
     * @author MbGenerated
     */
    private static final long serialVersionUID = 8833567223124603026L;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column admin_right.admin_id
     *
     * @author MbGenerated
     */
    private Integer adminId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column admin_right.sub_menu_id
     *
     * @author MbGenerated
     */
    private Integer subMenuId;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column admin_right.admin_id
     *
     * @return the value of admin_right.admin_id
     *
     * @author MbGenerated
     */
    public Integer getAdminId() {
        return adminId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column admin_right.admin_id
     *
     * @param adminId the value for admin_right.admin_id
     *
     * @author MbGenerated
     */
    public void setAdminId(Integer adminId) {
        this.adminId = adminId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column admin_right.sub_menu_id
     *
     * @return the value of admin_right.sub_menu_id
     *
     * @author MbGenerated
     */
    public Integer getSubMenuId() {
        return subMenuId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column admin_right.sub_menu_id
     *
     * @param subMenuId the value for admin_right.sub_menu_id
     *
     * @author MbGenerated
     */
    public void setSubMenuId(Integer subMenuId) {
        this.subMenuId = subMenuId;
    }
}