package com.tecapro.inventory.common.model;

import java.io.Serializable;

public class AdminRight extends AdminRightKey implements Serializable {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table admin_right
     *
     * @author MbGenerated
     */
    private static final long serialVersionUID = -7756538752955722821L;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column admin_right.read_only
     *
     * @author MbGenerated
     */
    private Integer readOnly;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column admin_right.insert_right
     *
     * @author MbGenerated
     */
    private Integer insertRight;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column admin_right.update_right
     *
     * @author MbGenerated
     */
    private Integer updateRight;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column admin_right.delete_right
     *
     * @author MbGenerated
     */
    private Integer deleteRight;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column admin_right.read_only
     *
     * @return the value of admin_right.read_only
     *
     * @author MbGenerated
     */
    public Integer getReadOnly() {
        return readOnly;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column admin_right.read_only
     *
     * @param readOnly the value for admin_right.read_only
     *
     * @author MbGenerated
     */
    public void setReadOnly(Integer readOnly) {
        this.readOnly = readOnly;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column admin_right.insert_right
     *
     * @return the value of admin_right.insert_right
     *
     * @author MbGenerated
     */
    public Integer getInsertRight() {
        return insertRight;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column admin_right.insert_right
     *
     * @param insertRight the value for admin_right.insert_right
     *
     * @author MbGenerated
     */
    public void setInsertRight(Integer insertRight) {
        this.insertRight = insertRight;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column admin_right.update_right
     *
     * @return the value of admin_right.update_right
     *
     * @author MbGenerated
     */
    public Integer getUpdateRight() {
        return updateRight;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column admin_right.update_right
     *
     * @param updateRight the value for admin_right.update_right
     *
     * @author MbGenerated
     */
    public void setUpdateRight(Integer updateRight) {
        this.updateRight = updateRight;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column admin_right.delete_right
     *
     * @return the value of admin_right.delete_right
     *
     * @author MbGenerated
     */
    public Integer getDeleteRight() {
        return deleteRight;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column admin_right.delete_right
     *
     * @param deleteRight the value for admin_right.delete_right
     *
     * @author MbGenerated
     */
    public void setDeleteRight(Integer deleteRight) {
        this.deleteRight = deleteRight;
    }
}