package com.tecapro.inventory.common.model;

import java.io.Serializable;

public class LogTransactionKey implements Serializable {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table log_transaction
     *
     * @author MbGenerated
     */
    private static final long serialVersionUID = -7505808518234739884L;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column log_transaction.id
     *
     * @author MbGenerated
     */
    private Long id;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column log_transaction.id
     *
     * @return the value of log_transaction.id
     *
     * @author MbGenerated
     */
    public Long getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column log_transaction.id
     *
     * @param id the value for log_transaction.id
     *
     * @author MbGenerated
     */
    public void setId(Long id) {
        this.id = id;
    }
}