package com.tecapro.inventory.common.model;

import java.io.Serializable;
import java.util.Date;

public class LogTransaction extends LogTransactionKey implements Serializable {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table log_transaction
     *
     * @author MbGenerated
     */
    private static final long serialVersionUID = 8107155778928037802L;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column log_transaction.datetime
     *
     * @author MbGenerated
     */
    private Date datetime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column log_transaction.msisdn
     *
     * @author MbGenerated
     */
    private String msisdn;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column log_transaction.action
     *
     * @author MbGenerated
     */
    private String action;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column log_transaction.source
     *
     * @author MbGenerated
     */
    private String source;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column log_transaction.error_code
     *
     * @author MbGenerated
     */
    private String errorCode;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column log_transaction.content
     *
     * @author MbGenerated
     */
    private String content;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column log_transaction.fee
     *
     * @author MbGenerated
     */
    private Integer fee;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column log_transaction.datetime
     *
     * @return the value of log_transaction.datetime
     *
     * @author MbGenerated
     */
    public Date getDatetime() {
        return datetime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column log_transaction.datetime
     *
     * @param datetime the value for log_transaction.datetime
     *
     * @author MbGenerated
     */
    public void setDatetime(Date datetime) {
        this.datetime = datetime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column log_transaction.msisdn
     *
     * @return the value of log_transaction.msisdn
     *
     * @author MbGenerated
     */
    public String getMsisdn() {
        return msisdn;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column log_transaction.msisdn
     *
     * @param msisdn the value for log_transaction.msisdn
     *
     * @author MbGenerated
     */
    public void setMsisdn(String msisdn) {
        this.msisdn = msisdn == null ? null : msisdn.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column log_transaction.action
     *
     * @return the value of log_transaction.action
     *
     * @author MbGenerated
     */
    public String getAction() {
        return action;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column log_transaction.action
     *
     * @param action the value for log_transaction.action
     *
     * @author MbGenerated
     */
    public void setAction(String action) {
        this.action = action == null ? null : action.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column log_transaction.source
     *
     * @return the value of log_transaction.source
     *
     * @author MbGenerated
     */
    public String getSource() {
        return source;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column log_transaction.source
     *
     * @param source the value for log_transaction.source
     *
     * @author MbGenerated
     */
    public void setSource(String source) {
        this.source = source == null ? null : source.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column log_transaction.error_code
     *
     * @return the value of log_transaction.error_code
     *
     * @author MbGenerated
     */
    public String getErrorCode() {
        return errorCode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column log_transaction.error_code
     *
     * @param errorCode the value for log_transaction.error_code
     *
     * @author MbGenerated
     */
    public void setErrorCode(String errorCode) {
        this.errorCode = errorCode == null ? null : errorCode.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column log_transaction.content
     *
     * @return the value of log_transaction.content
     *
     * @author MbGenerated
     */
    public String getContent() {
        return content;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column log_transaction.content
     *
     * @param content the value for log_transaction.content
     *
     * @author MbGenerated
     */
    public void setContent(String content) {
        this.content = content == null ? null : content.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column log_transaction.fee
     *
     * @return the value of log_transaction.fee
     *
     * @author MbGenerated
     */
    public Integer getFee() {
        return fee;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column log_transaction.fee
     *
     * @param fee the value for log_transaction.fee
     *
     * @author MbGenerated
     */
    public void setFee(Integer fee) {
        this.fee = fee;
    }
}