package com.tecapro.inventory.common.dao.impl;

import org.apache.ibatis.session.SqlSession;
import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.stereotype.Repository;

import com.tecapro.inventory.common.dao.AdminDao;
import com.tecapro.inventory.common.exception.UniqueKeyException;
import com.tecapro.inventory.common.model.Admin;
import com.tecapro.inventory.common.model.AdminKey;

@Repository("AdminDao")
public class AdminDaoImpl implements AdminDao {
    private String namespace = "com.tecapro.inventory.common.dao.AdminDao";

    @Autowired
    private SqlSession sqlSession;

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table admin
     *
     * @author MbGenerated
     */
    @Override
    public int selectCount(Admin record) {
        String query = namespace + ".selectCount";
        return sqlSession.selectOne(query, record);
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table admin
     *
     * @author MbGenerated
     */
    @Override
    public Admin selectByPK(AdminKey key) {
        String query = namespace + ".selectByPK";
        return sqlSession.selectOne(query, key);
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table admin
     *
     * @author MbGenerated
     */
    @Override
    public Admin selectForUpdateByPK(AdminKey key) {
        String query = namespace + ".selectForUpdateByPK";
        return sqlSession.selectOne(query, key);
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table admin
     *
     * @author MbGenerated
     */
    @Override
    public int insert(Admin record) throws UniqueKeyException {
        String query = namespace + ".insert";
        return sqlSession.insert(query, record);
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table admin
     *
     * @author MbGenerated
     */
    @Override
    public int update(Admin record) throws Throwable {
        String query = namespace + ".update";
        return sqlSession.update(query, record);
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table admin
     *
     * @author MbGenerated
     */
    @Override
    public int deleteByPK(AdminKey key) throws Throwable {
        String query = namespace + ".deleteByPK";
        return sqlSession.delete(query, key);
    }
}